wmap2019-django-master/app/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
# from django.core.urlresolvers import reverse

from . import views

app_name = 'app'

urlpatterns = [
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^$', views.landing, name='landing'),
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^userprofile/$', views.UserProfile.as_view(), name='userprofile'),
]

wmap2019-django-master/wmap2018_modified/urls.py
from django.conf.urls import url, include
from django.contrib.gis import admin
from rest_framework.authtoken import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include(('rest_framework.urls'), namespace='rest_framework')),
    url(r'^api-token-auth/', views.obtain_auth_token),
    url('', include(('app.urls'), namespace="app")),
    url(r'^rest/', include(('app.rest_urls'), namespace="rest")),
]

wmap2019-django-master/templates/app/base.html
<!DOCTYPE HTML>
<html>
  <head>
    <title>Pothole Demo</title>
      {% load static %}
    <style type="text/css">
      html, body, #basicMap {
          width: 100%;
          height: 100%;
          margin: 0;
      }
    </style>
    <script src="{% static "app/js/OpenLayers.js" %}"></script>
    <script>
      function init() {
        map = new OpenLayers.Map("basicMap");
        var mapnik         = new OpenLayers.Layer.OSM();
        var fromProjection = new OpenLayers.Projection("EPSG:4326");   // Transform from WGS 1984
        var toProjection   = new OpenLayers.Projection("EPSG:900913"); // to Spherical Mercator Projection
        var position       = new OpenLayers.LonLat(-6.27,53.34).transform( fromProjection, toProjection);
        var zoom           = 14;

        var lonLat1 = new OpenLayers.LonLat(0.1062,51.5171);

        var markers = new OpenLayers.Layer.Markers( "Markers" );
    map.addLayer(markers);
    markers.addMarker(new OpenLayers.Marker(position));
    markers.addMarker(new OpenLayers.Marker(lonLat1));
        map.addLayer(mapnik);
        map.setCenter(position, zoom );
      }
    </script>
  </head>
  <body onload="init();">

  <header>
    <table style="width: 100%">
        <tr>
            <td class="app-header" style="text-align: center; width: 100%;">
                Pothole Location - Sample Application
            </td>
        </tr>
    </table>
</header>
    <div id="basicMap"></div>
  </body>
</html>

wmap2019-django-master/templates/app/index.html
<!DOCTYPE html>
<html>
<head>
    <title>WMAP 2018</title>

    <meta http-equiv="Content-Security-Policy"
          content="default-src 'self' data: gap: https://ssl.gstatic.com
                http://localhost:8000 http://localhost:8002 http://192.168.1.9:8000 http://147.252.146.243:8000
              http://mf1.dit.ie:8511 http://mf1.dit.ie:81 http://mf1.dit.ie:82 http://mf2.dit.ie:8080
              https://*.tile.openstreetmap.org https://*.tile.osm.org
              http://*.tile.openstreetmap.org http://*.tile.osm.org
              https://router.project-osrm.org
              'unsafe-eval';
              style-src 'self' 'unsafe-inline';
              script-src 'self' 'unsafe-inline';
              media-src *">

    <meta name="format-detection" content="telephone=no">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="viewport"
          content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">

    <link rel="stylesheet" type="text/css" href="downloads/jquery-mobile/jquery.mobile-1.4.5.min.css">
    <link rel="stylesheet" type="text/css" href="downloads/font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="downloads/leaflet-1.0.3/leaflet.css">
    <link rel="stylesheet" type="text/css" href="downloads/leaflet.extramarkers/css/leaflet.extra-markers.min.css">
    <link rel="stylesheet" type="text/css" href="css/index.css">
    <link rel="stylesheet" type="text/css" href="css/style1.css">

    <link rel="stylesheet" href="downloads/leaflet-routing-machine-3.2.7/dist/leaflet-routing-machine.css"/>
    <link rel="stylesheet" href="downloads/leaflet-control-geocoder-1.5.7/dist/Control.Geocoder.css"/>

    <script src="downloads/jquery/jquery-1.12.4.js"></script>
    <script src="downloads/jquery-mobile/jquery.mobile-1.4.5.min.js"></script>
    <script src="downloads/leaflet-1.0.3/leaflet.js"></script>
    <script src="downloads/leaflet.extramarkers/js/leaflet.extra-markers.min.js"></script>
    <script src="downloads/leaflet-routing-machine-3.2.7/dist/leaflet-routing-machine.js"></script>
    <script src="downloads/leaflet-control-geocoder-1.5.7/dist/Control.Geocoder.js"></script>
    <script type="text/javascript" src="cordova.js"></script>
    <script type="text/javascript" src="js/index.js" crossorigin="anonymous"></script>
</head>

<body onload="onLoad();">

<div data-role="page" style="background-color: white" id="main-page">
    <div id="main-div" data-role="main" class="ui-content">
        <h1>Main Page placeholder2</h1>
    </div>
    <div data-role="header" style="text-align:center; background-color: rgba(255,255,255,0.8);" data-position="fixed"
         data-tap-toggle="false">
        <table style="width: 100%">
            <tr>
                <td style="text-align: left; vertical-align: middle; width: 85%">
                    <span style="font-size: large">Web Mapping 2018</span>
                </td>
                <td style="text-align: right; vertical-align: middle; width: 15%">
                    <span class="sp-username"></span>&nbsp;
                    <span class="plain-a" id="sp-logout">
                        <i class='fa fa-sign-out fa-3x'></i></span>
                </td>
            </tr>
        </table>
    </div>
    <div data-role="footer" data-id="main-foot" class="ui-header ui-bar-a" role="banner" data-position="fixed"
         style="text-align:center; background-color: rgba(255,255,255,0.2);" data-tap-toggle="false">
        <table>
            <tr>
                <td style="text-align: left; vertical-align: middle; width: 10%">
                    <a href="#map-page" id="goto-map" class="ui-btn-mini ui-btn-inline">
                        <span class="fa fa-map fa-2x" style="color:lightslategrey"></span>
                    </a>
                </td>
                <td></td>
                <td></td>
            </tr>
        </table>
    </div>
</div>


<div data-role="page" style="background-color: white" id="map-page">
    <!--
    <div data-role="header" style="text-align:center; background-color: rgba(255,255,255,0.8);" data-position="fixed"
         data-tap-toggle="false">
        <table style="width: 100%">
            <tr>
                <td style="text-align: left; vertical-align: middle; width: 85%">
                    <span style="font-size: large">Web Mapping 2018</span>
                </td>
                <td style="text-align: right; vertical-align: middle; width: 15%">
                    <span class="sp-username"></span>&nbsp;
                    <span class="plain-a" id="sp-logout">
                        <i class='fa fa-sign-out fa-3x'></i></span>
                </td>
            </tr>
        </table>
    </div>
    -->
    <div id="map-var" style="width: 100%; height: 100%;"></div>
    <div data-role="header" style="text-align:center; background-color: rgba(255,255,255,0.2);" data-position="fixed"
         data-tap-toggle="false">
        <table style="width: 100%">
            <tr>
                <td style="text-align: left; vertical-align: middle; width: 10%">
                    <a id="goto-currentlocation" class="ui-btn-mini ui-btn-inline">
                        <span class="fa fa-crosshairs fa-3x" style="color:deepskyblue"></span>
                    </a>
                </td>
                <td style="text-align: right">
                    <input id="amenity-search-text" type="text" placeholder="Amenity Search">
                </td>
                <td style="width: 10%">
                    <button id="amenity-search-button" type="button" class="ui-btn ui-corner-all ui-mini ui-btn-inline"
                            style="color: white; background-color: forestgreen">Go
                    </button>
                </td>
            </tr>
        </table>
        <span id="leaflet-copyright" style="font-size: xx-small"></span>
    </div>
    <div data-role="footer" data-id="main-foot" class="ui-header ui-bar-a" role="banner" data-position="fixed" style="text-align:center; background-color: rgba(255,255,255,0.2);" data-tap-toggle="false">
        <button id="btn-fav" type="button" >
            Favourite
        </button>
        <button id="btn-navigate" type="button" >
            Navigate
        </button>
    </div>


</div>

<div data-role="page" data-dialog="true" data-close-btn="none" style="background-color: white" id="login-page">
    <div data-role="header" style="text-align: center; background-color: silver">
        <span style="font-size: x-large">Web Mapping 2018</span>
    </div>

    <div data-role="main" class="ui-content"
         style="align-content: center; background-color: white">
        <form role="form">
            <div class="ui-field-contain">
                <label id="label-in-username" for="in-username"><span class="fa fa-user fa-fw"></span></label>
                <input type="text" class="form-control" id="in-username" placeholder="Username">
                <label id="label-in-password" for="in-password"><span class="fa fa-lock fa-fw"></span></label>
                <input type="password" class="form-control" id="in-password" placeholder="Password">
            </div>
            <button id="btn-login" type="button" class="ui-btn ui-corner-all live-button"
                    style="background-color: #669966; color: white;">
                <span class="fa fa-sign-in fa-lg"></span> Log In
            </button>
        </form>
    </div>
</div>

</body>
</html>

wmap2019-django-master/templates/app/landing.html
{% extends "app/base.html" %}

{% load staticfiles %}

{% block content %}
    <p>General landing page. This is a <em>placeholder</em> pending development.</p>
{% endblock %}

wmap2019-django-master/templates/app/login.html
{% extends "app/base.html" %}

{% load staticfiles %}

{% block content %}
    <h3>Log In</h3>

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <p><span class="error">
                    <strong>{{ error|escape }}</strong>
                </span></p>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <p><span class="error">
                <strong>{{ error|escape }}</strong>
            </span></p>
        {% endfor %}
    {% endif %}


    {% if user.is_authenticated %}
        <p class="error">You are already logged in.</p>
    {% else %}

        <form method="post" action="{% url 'app:login' %}">
            {% csrf_token %}
            <table>
{#                <tr>#}
{#                    <td>{{ form.username.label_tag }}</td>#}
{#                    <td>{{ form.username }}</td>#}
{#                </tr>#}
{#                <tr>#}
{#                    <td>{{ form.password.label_tag }}</td>#}
{#                    <td>{{ form.password }}</td>#}
{#                </tr>#}
                {{ form.as_table }}
            </table>

            <input type="submit" value="Log In"/>
        </form>
    {% endif %}

{% endblock %}

wmap2019-django-master/templates/app/logout.html
{% extends "app/base.html" %}

{% load staticfiles %}

{% block content %}
    <p>Thank you for visiting. Come back soon.</p>
{% endblock %}

wmap2019-django-master/templates/app/pothole_map.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

wmap2019-django-master/templates/app/signup.html
{% extends "app/base.html" %}

{% load staticfiles %}

{% block content %}
    <h3>Sign Up</h3>

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <p><span class="error">
                    <strong>{{ error|escape }}</strong>
                </span></p>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <p><span class="error">
                <strong>{{ error|escape }}</strong>
            </span></p>
        {% endfor %}
    {% endif %}

    {% if user.is_authenticated %}
        <p class="error">You are already logged in.</p>
    {% else %}

        <form method="post" action="{% url 'app:signup' %}">
            {% csrf_token %}
            <table>
                <tr>
                    <td>{{ form.username.label_tag }}</td>
                    <td>{{ form.username }}</td>
                </tr>
                <tr>
                    <td>{{ form.password.label_tag }}</td>
                    <td>{{ form.password }}</td>
                </tr>
                <tr>
                    <td>{{ form.password2.label_tag }}</td>
                    <td>{{ form.password2 }}</td>
                </tr>
                <tr>
                    <td>{{ form.first_name.label_tag }}</td>
                    <td>{{ form.first_name }}</td>
                </tr>
                <tr>
                    <td>{{ form.last_name.label_tag }}</td>
                    <td>{{ form.last_name }}</td>
                </tr>
                <tr>
                    <td>{{ form.email.label_tag }}</td>
                    <td>{{ form.email }}</td>
                </tr>
            </table>

            <input type="submit" value="Sign Up"/>
        </form>
    {% endif %}

{% endblock %}

wmap2019-django-master/templates/app/user_profile.html
{% extends "app/base.html" %}

{% load staticfiles %}
{% load leaflet_tags %}

{% block content %}
    <h3>User Profile</h3>

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <p><span class="error">
                    <strong>{{ error|escape }}</strong>
                </span></p>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <p><span class="error">
                <strong>{{ error|escape }}</strong>
            </span></p>
        {% endfor %}
    {% endif %}

    {% if user.is_authenticated %}
        <form method="post" action="{% url 'app:userprofile' %}">
            {% csrf_token %}
            <table style="padding: 10px; width: 100%">
                <tr>
                    <td style="text-align: right; font-family: sans-serif, Arial; font-style: italic; font-weight: normal">
                        Username
                    </td>
                    <td style="font-family: sans-serif, Arial; font-style: italic; font-weight: bold">{{ object.username }}</td>
                </tr>
                <tr>
                    <td style="text-align: right; font-family: sans-serif, Arial; font-style: italic; font-weight: normal">
                        Last login
                    </td>
                    <td style="font-family: sans-serif, Arial; font-style: italic; font-weight: bold">{{ object.last_login }}</td>
                </tr>
                <tr>
                    <td style="text-align: right;">{{ form.first_name.label_tag }}</td>
                    <td>{{ form.first_name }}</td>
                </tr>
                <tr>
                    <td style="text-align: right;">{{ form.last_name.label_tag }}</td>
                    <td>{{ form.last_name }}</td>
                </tr>
                <tr>
                    <td style="text-align: right;">{{ form.email.label_tag }}</td>
                    <td>{{ form.email }}</td>
                </tr>
                <tr>
                    <td style="text-align: right;"></td>
                    <td><input type="submit" value="Update Profile"/></td>
                </tr>
                {#                {{ form.as_table }}#}
            </table>


        </form>
    {% else %}
        <p class="error">You are not logged in.</p>
    {% endif %}

    <p id="geom" style="visibility: hidden; display: none">{{ object.last_location.geojson }}</p>

    <script>
        function map_init(map, options) {
            var geom = JSON.parse($("#geom").html());
            var myLatLon = L.latLng([geom.coordinates[1], geom.coordinates[0]]);

            geom = L.geoJson(geom);
            geom.addTo(map);

            map.setView(myLatLon, 16);
        }
    </script>

    <h3>Last known location</h3>
    <div style="text-align: center">
        {% leaflet_map "my_map" callback="map_init" %}
    </div>

{% endblock %}